/**
 * Roleplay scenarios catalog.
 *
 * Each scenario gives the tutor a specific role to play and the user a clear
 * goal. The AI plays the "other side" of the conversation (waiter, doctor,
 * coworker, etc.) and grades the user on success criteria at the end of the
 * session. All copy below is in English; the AI conducts the actual roleplay
 * in the user's target language, calibrated to their CEFR level.
 *
 * `level` is the recommended CEFR fit (A1 | A2 | B1 | B2 | C1). The picker
 * groups by user level; the AI also reads memory.proficiencyLevel and adapts
 * vocabulary/sentence length at runtime.
 */

const SCENARIOS = [
  // ===================== A1 — true beginner =====================
  {
    id: 'coffee_shop',
    emoji: '☕',
    title: 'Order a coffee',
    summary: 'Casual coffee shop order — quick and friendly.',
    goal: 'Order your drink with one customization.',
    aiRole: 'a chatty barista',
    level: 'A1',
    successCriteria: [
      'User ordered a specific drink',
      'User specified one customization (size, milk, sugar...)',
      'User responded to small talk',
    ],
    minTurns: 4,
  },
  {
    id: 'supermarket_find',
    emoji: '🛒',
    title: 'Find an item in a supermarket',
    summary: 'Ask an employee where to find something on the shelves.',
    goal: 'Locate one item and thank the employee.',
    aiRole: 'a supermarket employee restocking shelves',
    level: 'A1',
    successCriteria: [
      'User greeted the employee',
      'User asked where to find a specific item',
      'User confirmed they understood the answer',
    ],
    minTurns: 3,
  },
  {
    id: 'greet_neighbor',
    emoji: '👋',
    title: 'Greet a neighbor in the elevator',
    summary: 'A short, polite exchange with someone from your building.',
    goal: 'Greet them, exchange one line of small talk, say goodbye.',
    aiRole: 'a friendly elderly neighbor you see most mornings',
    level: 'A1',
    successCriteria: [
      'User greeted appropriately for the time of day',
      'User responded to small talk (weather, weekend...)',
      'User said goodbye politely',
    ],
    minTurns: 3,
  },
  {
    id: 'metro_ticket',
    emoji: '🎫',
    title: 'Buy a metro ticket',
    summary: 'Buy a single ticket at the metro counter.',
    goal: 'Buy a ticket for the correct destination and pay.',
    aiRole: 'a metro station ticket-counter attendant',
    level: 'A1',
    successCriteria: [
      'User asked for a ticket to a specific destination',
      'User understood the price',
      'User paid and thanked the attendant',
    ],
    minTurns: 4,
  },
  {
    id: 'self_intro',
    emoji: '🪪',
    title: 'Introduce yourself',
    summary: 'Tell someone your name, where you are from, and what you do.',
    goal: 'Share three facts about yourself and ask one back.',
    aiRole: 'a friendly student in a beginner language class',
    level: 'A1',
    successCriteria: [
      'User said their name',
      'User said where they are from',
      'User asked the other person at least one question',
    ],
    minTurns: 4,
  },
  {
    id: 'ask_time',
    emoji: '⏰',
    title: 'Ask what time it is',
    summary: 'A stranger on the street has a watch — get the time.',
    goal: 'Ask politely and thank them.',
    aiRole: 'a stranger waiting at a bus stop',
    level: 'A1',
    successCriteria: [
      'User got the stranger\'s attention politely',
      'User asked for the time',
      'User thanked them',
    ],
    minTurns: 3,
  },
  {
    id: 'bakery',
    emoji: '🥖',
    title: 'Buy bread at a bakery',
    summary: 'Order a few items at a small neighborhood bakery.',
    goal: 'Order at least two items and pay.',
    aiRole: 'a cheerful baker behind the counter',
    level: 'A1',
    successCriteria: [
      'User asked for at least two specific items',
      'User asked for the total or understood the price',
      'User paid and said goodbye',
    ],
    minTurns: 4,
  },
  {
    id: 'bathroom_directions',
    emoji: '🚻',
    title: 'Ask where the bathroom is',
    summary: 'In a cafe — ask politely and follow short directions.',
    goal: 'Find out where the bathroom is.',
    aiRole: 'a cafe server clearing tables',
    level: 'A1',
    successCriteria: [
      'User got the server\'s attention',
      'User asked for the bathroom',
      'User confirmed the directions or said thank you',
    ],
    minTurns: 3,
  },

  // ===================== A2 — basic survival =====================
  {
    id: 'restaurant_order',
    emoji: '🍝',
    title: 'Order at a restaurant',
    summary: 'Order a meal, ask about ingredients, request the bill.',
    goal: 'Successfully order a 2-course meal and pay.',
    aiRole: 'a friendly waiter at a casual restaurant',
    level: 'A2',
    successCriteria: [
      'User greeted the waiter',
      'User ordered a main course',
      'User asked at least one question about the menu',
      'User asked for the bill politely',
    ],
    minTurns: 6,
  },
  {
    id: 'asking_directions',
    emoji: '🧭',
    title: 'Ask for directions',
    summary: 'Find your way to a landmark using only spoken directions.',
    goal: 'Get clear directions to the nearest train station.',
    aiRole: 'a helpful local on the street',
    level: 'A2',
    successCriteria: [
      'User politely got the local\'s attention',
      'User asked for the train station',
      'User confirmed they understood (or asked for repetition)',
      'User thanked the local',
    ],
    minTurns: 5,
  },
  {
    id: 'hotel_checkin',
    emoji: '🏨',
    title: 'Check in at a hotel',
    summary: 'Confirm your reservation, ask about amenities.',
    goal: 'Check in successfully and find out about breakfast hours.',
    aiRole: 'a friendly hotel front-desk clerk',
    level: 'A2',
    successCriteria: [
      'User confirmed name and booking',
      'User asked about at least one amenity (breakfast, wifi, gym...)',
      'User asked for a wake-up call OR late checkout',
    ],
    minTurns: 5,
  },
  {
    id: 'doctor_visit',
    emoji: '🩺',
    title: 'Doctor visit',
    summary: 'Describe a symptom and ask follow-up questions.',
    goal: 'Get a clear next-step recommendation from the doctor.',
    aiRole: 'a calm general-practice doctor',
    level: 'A2',
    successCriteria: [
      'User described a symptom with duration',
      'User answered the doctor\'s clarifying question',
      'User asked about treatment OR follow-up',
    ],
    minTurns: 6,
  },
  {
    id: 'taxi_ride',
    emoji: '🚕',
    title: 'Take a taxi',
    summary: 'Tell a driver where you want to go and make small talk.',
    goal: 'Get to your destination and confirm the fare.',
    aiRole: 'a talkative taxi driver',
    level: 'A2',
    successCriteria: [
      'User gave a clear destination',
      'User responded to at least one small-talk question',
      'User asked about the fare or paid politely',
    ],
    minTurns: 5,
  },
  {
    id: 'pharmacy',
    emoji: '💊',
    title: 'Buy medicine at a pharmacy',
    summary: 'Describe a common ailment and buy something for it.',
    goal: 'Walk out with the right medicine + dosage understood.',
    aiRole: 'a pharmacist behind the counter',
    level: 'A2',
    successCriteria: [
      'User described the symptom clearly',
      'User asked about dosage or side effects',
      'User confirmed price and paid',
    ],
    minTurns: 5,
  },
  {
    id: 'airport_checkin',
    emoji: '🛫',
    title: 'Airport check-in',
    summary: 'Check in for a flight at the airline counter.',
    goal: 'Get your boarding pass and check one bag.',
    aiRole: 'a check-in agent at a busy airline counter',
    level: 'A2',
    successCriteria: [
      'User showed passport / confirmed reservation',
      'User checked at least one bag',
      'User asked about gate or boarding time',
    ],
    minTurns: 5,
  },
  {
    id: 'store_return',
    emoji: '🛍️',
    title: 'Return a defective item',
    summary: 'Return something to a store and ask for a refund.',
    goal: 'Get either a refund or a working replacement.',
    aiRole: 'a customer-service clerk at a clothing store',
    level: 'A2',
    successCriteria: [
      'User explained what is wrong with the item',
      'User asked for a refund or exchange',
      'User showed receipt or proof of purchase',
    ],
    minTurns: 5,
  },
  {
    id: 'schedule_delivery',
    emoji: '📦',
    title: 'Schedule a package delivery',
    summary: 'Arrange a time window for a delivery to your home.',
    goal: 'Confirm a delivery slot and provide your address.',
    aiRole: 'a delivery-service phone operator',
    level: 'A2',
    successCriteria: [
      'User gave their address clearly',
      'User picked a time window',
      'User confirmed the booking',
    ],
    minTurns: 5,
  },

  // ===================== B1 — independent user =====================
  {
    id: 'job_interview',
    emoji: '💼',
    title: 'Job interview',
    summary: 'Introduce yourself, answer common interview questions.',
    goal: 'Make a strong first impression in a 5-minute interview.',
    aiRole: 'a professional hiring manager conducting a first-round interview',
    level: 'B1',
    successCriteria: [
      'User introduced themselves clearly',
      'User answered why they want the job',
      'User asked at least one question back',
      'User used appropriate formal register',
    ],
    minTurns: 8,
  },
  {
    id: 'meet_at_meetup',
    emoji: '🤝',
    title: 'Meet someone at a language exchange',
    summary: 'Casual chat with a stranger at a language meetup.',
    goal: 'Have a friendly 5-minute conversation and find something in common.',
    aiRole: 'another language learner you just met at the meetup',
    level: 'B1',
    successCriteria: [
      'User introduced themselves naturally',
      'User asked about the other person\'s background',
      'User found one shared interest',
      'User suggested keeping in touch',
    ],
    minTurns: 6,
  },
  {
    id: 'first_date',
    emoji: '💕',
    title: 'First date coffee chat',
    summary: 'Casual conversational practice on a first date.',
    goal: 'Keep the conversation going for 5+ exchanges and ask thoughtful questions.',
    aiRole: 'someone you matched with on a dating app — friendly but a little shy',
    level: 'B1',
    successCriteria: [
      'User asked about hobbies or work',
      'User shared something about themselves',
      'User reacted naturally to what the other person said',
      'User suggested a next step (or politely closed)',
    ],
    minTurns: 7,
  },
  {
    id: 'new_job_intro',
    emoji: '🏢',
    title: 'First day at a new job',
    summary: 'Meet a coworker on day one and learn the basics.',
    goal: 'Introduce yourself and ask about the team and routine.',
    aiRole: 'a friendly coworker showing you around the office',
    level: 'B1',
    successCriteria: [
      'User introduced themselves and their role',
      'User asked about the team',
      'User asked about office routines (lunch, hours, slack...)',
      'User used appropriate office register',
    ],
    minTurns: 6,
  },
  {
    id: 'isp_complaint',
    emoji: '📞',
    title: 'Call your internet provider',
    summary: 'Report an outage and ask for a fix or refund.',
    goal: 'Get a technician scheduled or credit on your bill.',
    aiRole: 'a customer-service rep at an internet provider, polite but a bit scripted',
    level: 'B1',
    successCriteria: [
      'User clearly described the problem',
      'User gave account info when asked',
      'User asked for a concrete next step (technician / credit)',
      'User confirmed the resolution',
    ],
    minTurns: 7,
  },
  {
    id: 'apartment_tour',
    emoji: '🏠',
    title: 'Tour an apartment with a landlord',
    summary: 'Visit a rental, ask questions, decide if you want to apply.',
    goal: 'Learn the rent, what is included, and the application process.',
    aiRole: 'a landlord showing the apartment',
    level: 'B1',
    successCriteria: [
      'User asked about rent and what is included',
      'User asked about at least one feature (heating, parking, pets...)',
      'User asked about the application process',
      'User politely indicated interest (or not)',
    ],
    minTurns: 6,
  },
  {
    id: 'bank_account',
    emoji: '🏦',
    title: 'Open a bank account',
    summary: 'Open a checking account and ask about fees.',
    goal: 'Open the account and walk out understanding the fee structure.',
    aiRole: 'a friendly bank teller',
    level: 'B1',
    successCriteria: [
      'User explained which type of account they want',
      'User provided ID / proof of address',
      'User asked about monthly fees or minimum balance',
      'User confirmed the account is open',
    ],
    minTurns: 7,
  },
  {
    id: 'weekend_plans',
    emoji: '🍳',
    title: 'Weekend plans with a coworker',
    summary: 'Friday coffee chat about plans for the weekend.',
    goal: 'Share your plans, ask about theirs, suggest meeting up.',
    aiRole: 'a friendly coworker you eat lunch with sometimes',
    level: 'B1',
    successCriteria: [
      'User shared their weekend plans',
      'User asked about the coworker\'s plans',
      'User suggested an activity together',
      'User used casual / informal register',
    ],
    minTurns: 5,
  },

  // ===================== B2 — upper-intermediate =====================
  {
    id: 'team_pitch',
    emoji: '📊',
    title: 'Pitch a project idea',
    summary: 'Propose a project at a team meeting; defend it against questions.',
    goal: 'Get conditional buy-in from the team lead.',
    aiRole: 'a skeptical team lead asking practical questions',
    level: 'B2',
    successCriteria: [
      'User explained the project in 2-3 sentences',
      'User addressed at least two concerns',
      'User proposed concrete next steps',
      'User used professional register',
    ],
    minTurns: 8,
  },
  {
    id: 'salary_negotiation',
    emoji: '💵',
    title: 'Negotiate salary at a review',
    summary: 'Performance review with a salary discussion.',
    goal: 'Argue for a specific raise number and reach an outcome.',
    aiRole: 'your manager during your annual performance review',
    level: 'B2',
    successCriteria: [
      'User named a specific number',
      'User justified the number with achievements',
      'User responded to pushback with concrete examples',
      'User reached either a number or a clear next step',
    ],
    minTurns: 8,
  },
  {
    id: 'current_event_debate',
    emoji: '🗳️',
    title: 'Debate a current event',
    summary: 'A friendly but real debate about a current topic.',
    goal: 'Defend your position and acknowledge the other side.',
    aiRole: 'a friend who holds the opposite view, civil but firm',
    level: 'B2',
    successCriteria: [
      'User stated their position clearly',
      'User gave at least two supporting reasons',
      'User acknowledged the opposing view',
      'User ended on a respectful note',
    ],
    minTurns: 8,
  },
  {
    id: 'wedding_toast',
    emoji: '🎤',
    title: 'Give a toast at a wedding',
    summary: 'Practice giving a short, warm toast as the AI judges.',
    goal: 'Deliver a 60-90 second toast with structure and emotion.',
    aiRole: 'a toastmaster cueing you and reacting afterwards',
    level: 'B2',
    successCriteria: [
      'User included a personal story about the couple',
      'User landed at least one warm or funny line',
      'User closed with a clear toast / cheers line',
      'User used appropriate emotional register',
    ],
    minTurns: 5,
  },
  {
    id: 'breakup_support',
    emoji: '💔',
    title: 'Comfort a friend after a breakup',
    summary: 'A friend calls upset; you listen and offer support.',
    goal: 'Make them feel heard without rushing to fix things.',
    aiRole: 'a close friend who is upset and just wants to talk',
    level: 'B2',
    successCriteria: [
      'User asked open questions to let them vent',
      'User validated their feelings before giving advice',
      'User offered concrete support (meet up, call later...)',
      'User used warm, informal register',
    ],
    minTurns: 7,
  },
  {
    id: 'career_mentor',
    emoji: '🎯',
    title: 'Career goals with a mentor',
    summary: 'A coffee with a senior mentor about your next career step.',
    goal: 'Leave with one concrete piece of advice you will act on.',
    aiRole: 'a thoughtful senior mentor who asks more than tells',
    level: 'B2',
    successCriteria: [
      'User described their current situation honestly',
      'User named a specific career question',
      'User asked at least one good follow-up question',
      'User summarized the advice and committed to a next step',
    ],
    minTurns: 8,
  },
  {
    id: 'investor_pitch',
    emoji: '🚀',
    title: 'Pitch a startup to an investor',
    summary: 'A 5-minute first pitch followed by tough questions.',
    goal: 'Get the investor to ask for a follow-up meeting.',
    aiRole: 'an early-stage investor — sharp, time-pressured, kind',
    level: 'B2',
    successCriteria: [
      'User opened with a clear problem statement',
      'User explained the solution in plain language',
      'User answered traction/market questions concretely',
      'User asked for a specific next step',
    ],
    minTurns: 8,
  },

  // ===================== C1 — advanced, nuanced =====================
  {
    id: 'academic_defense',
    emoji: '🎓',
    title: 'Defend a research idea',
    summary: 'Present a research idea in a graduate seminar; field hard questions.',
    goal: 'Defend your thesis without conceding the core argument.',
    aiRole: 'a sharp graduate-seminar discussant who finds the weakest link',
    level: 'C1',
    successCriteria: [
      'User stated the thesis precisely',
      'User responded to a methodological challenge with evidence',
      'User distinguished what is and is not in scope',
      'User used precise academic register',
    ],
    minTurns: 9,
  },
  {
    id: 'press_interview',
    emoji: '🎙️',
    title: 'Hostile press interview',
    summary: 'A journalist is probing for a soundbite. Stay on message.',
    goal: 'Deliver your key message without slipping into the gotcha frame.',
    aiRole: 'a probing journalist looking for a controversial soundbite',
    level: 'C1',
    successCriteria: [
      'User redirected at least one leading question',
      'User stayed on key message across 3+ turns',
      'User acknowledged a hard fact without conceding the frame',
      'User ended without saying anything quotable they would regret',
    ],
    minTurns: 8,
  },
  {
    id: 'contract_negotiation',
    emoji: '⚖️',
    title: 'Negotiate a tough contract',
    summary: 'Negotiate one critical clause with a hostile counterpart.',
    goal: 'Move the counterpart from their opening position to something workable.',
    aiRole: 'a sharp opposing-side lawyer with a strong opening stance',
    level: 'C1',
    successCriteria: [
      'User identified the core interest (not just the position)',
      'User used at least one principled-negotiation move',
      'User offered a concrete trade or alternative',
      'User closed with either a deal or a clear walk-away',
    ],
    minTurns: 9,
  },
  {
    id: 'senior_interview',
    emoji: '🏛️',
    title: 'Senior leadership behavioral interview',
    summary: 'STAR-format behavioral interview for a senior role.',
    goal: 'Land one story per behavioral competency with measurable outcomes.',
    aiRole: 'a senior executive interviewing for VP / Director role',
    level: 'C1',
    successCriteria: [
      'User used Situation-Task-Action-Result structure',
      'User cited measurable outcomes (numbers, %s, time)',
      'User reflected on what they would do differently',
      'User asked at least one sharp question about the role',
    ],
    minTurns: 9,
  },
  {
    id: 'funny_story',
    emoji: '📖',
    title: 'Tell a funny personal story',
    summary: 'Recount a real funny story to a small group — set up, build, land it.',
    goal: 'Get a real laugh by the end (and the AI will tell you if you got it).',
    aiRole: 'a small group of friends listening at a dinner party',
    level: 'C1',
    successCriteria: [
      'User set up the situation in 2-3 sentences',
      'User built tension with specific details',
      'User landed a clear punchline or twist',
      'User used appropriate informal/spoken register and rhythm',
    ],
    minTurns: 6,
  },
  {
    id: 'diplomatic_dinner',
    emoji: '🌍',
    title: 'Cultural-exchange dinner conversation',
    summary: 'A semi-formal dinner with people from different cultures.',
    goal: 'Discuss a sensitive cultural topic with curiosity and tact.',
    aiRole: 'a thoughtful dinner host from a different cultural background',
    level: 'C1',
    successCriteria: [
      'User asked a question that opened (not closed) the topic',
      'User shared a perspective without imposing it',
      'User noticed and adjusted to a moment of cultural difference',
      'User used register appropriate for a semi-formal dinner',
    ],
    minTurns: 8,
  },
  {
    id: 'workplace_mediation',
    emoji: '🤲',
    title: 'Mediate a workplace conflict',
    summary: 'Mediate between two colleagues with a real disagreement.',
    goal: 'Get both sides to commit to one shared next step.',
    aiRole: 'two colleagues — one frustrated, one defensive — taking turns speaking',
    level: 'C1',
    successCriteria: [
      'User let both sides describe the problem before reacting',
      'User reframed at least one accusation as an interest',
      'User proposed a concrete shared next step',
      'User got verbal agreement from both sides',
    ],
    minTurns: 10,
  },
];

const list = () => SCENARIOS.map(s => ({
  id: s.id,
  emoji: s.emoji,
  title: s.title,
  summary: s.summary,
  goal: s.goal,
  level: s.level,
  minTurns: s.minTurns,
}));

const findById = (id) => SCENARIOS.find(s => s.id === id);

module.exports = { list, findById };
