// Expanded language-specific vocabulary for exams
// 400+ words per language with 15+ topics each

const EXPANDED_VOCABULARY = {
  en: {
    name: 'English',
    A1: {
      'Family & Home': [
        { w: 'mother', p: 'noun', d: 'female parent', e: 'My mother is a teacher.' },
        { w: 'father', p: 'noun', d: 'male parent', e: 'My father works hard.' },
        { w: 'sister', p: 'noun', d: 'female sibling', e: 'My sister is 10 years old.' },
        { w: 'brother', p: 'noun', d: 'male sibling', e: 'I have two brothers.' },
        { w: 'family', p: 'noun', d: 'parents and children', e: 'Family is important.' },
        { w: 'house', p: 'noun', d: 'building where people live', e: 'We have a big house.' },
        { w: 'room', p: 'noun', d: 'space in a building', e: 'My bedroom is small.' },
        { w: 'door', p: 'noun', d: 'entrance to a room', e: 'Please close the door.' },
        { w: 'window', p: 'noun', d: 'opening in a wall', e: 'Open the window please.' },
        { w: 'kitchen', p: 'noun', d: 'room for cooking', e: 'I cook in the kitchen.' },
        { w: 'bed', p: 'noun', d: 'furniture for sleeping', e: 'I sleep in my bed.' },
        { w: 'chair', p: 'noun', d: 'furniture for sitting', e: 'Please sit in the chair.' },
        { w: 'table', p: 'noun', d: 'flat furniture surface', e: 'We eat at the table.' },
        { w: 'lamp', p: 'noun', d: 'object that gives light', e: 'Turn on the lamp.' },
        { w: 'phone', p: 'noun', d: 'device for calling', e: 'Call me on my phone.' },
      ],
      'Food & Drink': [
        { w: 'bread', p: 'noun', d: 'food made from flour', e: 'I eat bread daily.' },
        { w: 'water', p: 'noun', d: 'clear liquid', e: 'Drink water regularly.' },
        { w: 'apple', p: 'noun', d: 'round red/green fruit', e: 'An apple a day is healthy.' },
        { w: 'coffee', p: 'noun', d: 'hot drink', e: 'I drink coffee in the morning.' },
        { w: 'milk', p: 'noun', d: 'white liquid from animals', e: 'Milk is good for bones.' },
        { w: 'cheese', p: 'noun', d: 'dairy food', e: 'I like cheese and bread.' },
        { w: 'egg', p: 'noun', d: 'breakfast food from chickens', e: 'I eat an egg for breakfast.' },
        { w: 'chicken', p: 'noun', d: 'type of meat', e: 'We eat chicken for dinner.' },
        { w: 'rice', p: 'noun', d: 'grain staple food', e: 'I eat rice every day.' },
        { w: 'fish', p: 'noun', d: 'food from water', e: 'Fish is healthy to eat.' },
        { w: 'soup', p: 'noun', d: 'liquid food', e: 'Soup is warm and tasty.' },
        { w: 'salad', p: 'noun', d: 'vegetables mixed together', e: 'I eat a healthy salad.' },
        { w: 'tea', p: 'noun', d: 'hot drink from leaves', e: 'I drink tea in the afternoon.' },
        { w: 'juice', p: 'noun', d: 'drink from fruit', e: 'Orange juice is delicious.' },
        { w: 'sugar', p: 'noun', d: 'sweet substance', e: 'Add sugar to your coffee.' },
      ],
      'Numbers & Time': [
        { w: 'one', p: 'noun', d: 'number 1', e: 'I have one cat.' },
        { w: 'two', p: 'noun', d: 'number 2', e: 'We have two cars.' },
        { w: 'three', p: 'noun', d: 'number 3', e: 'There are three books.' },
        { w: 'ten', p: 'noun', d: 'number 10', e: 'Ten fingers on your hands.' },
        { w: 'hundred', p: 'noun', d: 'number 100', e: 'This book has 200 pages.' },
        { w: 'day', p: 'noun', d: '24-hour period', e: 'I work five days a week.' },
        { w: 'week', p: 'noun', d: 'seven days', e: 'I see my friend every week.' },
        { w: 'month', p: 'noun', d: 'about 30 days', e: 'January is the first month.' },
        { w: 'year', p: 'noun', d: '12 months', e: 'I am 25 years old.' },
        { w: 'hour', p: 'noun', d: '60 minutes', e: 'I work 8 hours a day.' },
        { w: 'minute', p: 'noun', d: '60 seconds', e: 'Wait five minutes please.' },
        { w: 'second', p: 'noun', d: '1/60 of a minute', e: 'Just a second please.' },
        { w: 'morning', p: 'noun', d: 'early part of day', e: 'I wake up in the morning.' },
        { w: 'afternoon', p: 'noun', d: 'middle of the day', e: 'I rest in the afternoon.' },
        { w: 'night', p: 'noun', d: 'dark time', e: 'I sleep at night.' },
      ],
      'Colors & Shapes': [
        { w: 'red', p: 'adjective', d: 'color like blood', e: 'She has a red car.' },
        { w: 'blue', p: 'adjective', d: 'color of sky', e: 'The sky is blue.' },
        { w: 'green', p: 'adjective', d: 'color of grass', e: 'Trees are green.' },
        { w: 'yellow', p: 'adjective', d: 'color of sun', e: 'The flower is yellow.' },
        { w: 'white', p: 'adjective', d: 'color of snow', e: 'His shirt is white.' },
        { w: 'black', p: 'adjective', d: 'darkest color', e: 'I have a black pen.' },
        { w: 'circle', p: 'noun', d: 'round shape', e: 'A ball is a circle.' },
        { w: 'square', p: 'noun', d: 'four equal sides', e: 'A box is a square.' },
        { w: 'triangle', p: 'noun', d: 'three-sided shape', e: 'A pyramid has triangles.' },
        { w: 'line', p: 'noun', d: 'straight mark', e: 'Draw a line please.' },
      ],
      'Body Parts': [
        { w: 'head', p: 'noun', d: 'top of body', e: 'I have a head on my shoulders.' },
        { w: 'arm', p: 'noun', d: 'limb for movement', e: 'I have two arms.' },
        { w: 'leg', p: 'noun', d: 'limb for walking', e: 'I have two legs.' },
        { w: 'hand', p: 'noun', d: 'end of arm', e: 'I have two hands.' },
        { w: 'foot', p: 'noun', d: 'end of leg', e: 'I have two feet.' },
        { w: 'eye', p: 'noun', d: 'organ for seeing', e: 'I have two eyes.' },
        { w: 'ear', p: 'noun', d: 'organ for hearing', e: 'I have two ears.' },
        { w: 'nose', p: 'noun', d: 'organ for smelling', e: 'I have one nose.' },
        { w: 'mouth', p: 'noun', d: 'for eating and speaking', e: 'I use my mouth to eat.' },
        { w: 'tooth', p: 'noun', d: 'in mouth for eating', e: 'I have white teeth.' },
      ],
    },
    B1: {
      'Business & Work': [
        { w: 'profit', p: 'noun', d: 'money earned after costs', e: 'The company made a large profit.' },
        { w: 'investment', p: 'noun', d: 'money to gain return', e: 'Real estate is a good investment.' },
        { w: 'market', p: 'noun', d: 'place of trade', e: 'The stock market was up.' },
        { w: 'entrepreneur', p: 'noun', d: 'business starter', e: 'She is a successful entrepreneur.' },
        { w: 'contract', p: 'noun', d: 'legal agreement', e: 'We signed the contract yesterday.' },
        { w: 'salary', p: 'noun', d: 'payment for work', e: 'My salary is paid monthly.' },
        { w: 'employee', p: 'noun', d: 'person who works', e: 'The company has 500 employees.' },
        { w: 'employer', p: 'noun', d: 'person who hires', e: 'My employer is very kind.' },
        { w: 'colleague', p: 'noun', d: 'coworker', e: 'I work with my colleague.' },
        { w: 'office', p: 'noun', d: 'workplace building', e: 'I work in a big office.' },
        { w: 'conference', p: 'noun', d: 'business meeting', e: 'We have a conference tomorrow.' },
        { w: 'deadline', p: 'noun', d: 'final date', e: 'The deadline is Friday.' },
        { w: 'budget', p: 'noun', d: 'money plan', e: 'We have a tight budget.' },
        { w: 'revenue', p: 'noun', d: 'money earned', e: 'Our revenue increased this year.' },
        { w: 'expense', p: 'noun', d: 'money spent', e: 'Business expenses are high.' },
      ],
      'Technology': [
        { w: 'software', p: 'noun', d: 'computer programs', e: 'This software is user-friendly.' },
        { w: 'database', p: 'noun', d: 'organized data', e: 'The database contains customer info.' },
        { w: 'interface', p: 'noun', d: 'connecting device', e: 'The interface is easy to use.' },
        { w: 'algorithm', p: 'noun', d: 'step-by-step procedure', e: 'The algorithm solves quickly.' },
        { w: 'bandwidth', p: 'noun', d: 'data capacity', e: 'We need more bandwidth.' },
        { w: 'server', p: 'noun', d: 'main computer', e: 'The server is down.' },
        { w: 'cloud', p: 'noun', d: 'remote storage', e: 'Save your files to the cloud.' },
        { w: 'network', p: 'noun', d: 'connected computers', e: 'The network is secure.' },
        { w: 'security', p: 'noun', d: 'protection system', e: 'Security is important online.' },
        { w: 'encryption', p: 'noun', d: 'data protection', e: 'Encryption keeps data safe.' },
        { w: 'cyber', p: 'adjective', d: 'computer-related', e: 'Cyber attacks are dangerous.' },
        { w: 'digital', p: 'adjective', d: 'using computers', e: 'Digital transformation is happening.' },
        { w: 'virtual', p: 'adjective', d: 'not physical', e: 'Virtual meetings are common.' },
        { w: 'artificial', p: 'adjective', d: 'man-made', e: 'Artificial intelligence is growing.' },
        { w: 'innovation', p: 'noun', d: 'new creation', e: 'Innovation drives progress.' },
      ],
      'Education': [
        { w: 'university', p: 'noun', d: 'higher learning place', e: 'I study at university.' },
        { w: 'student', p: 'noun', d: 'person learning', e: 'The student works hard.' },
        { w: 'teacher', p: 'noun', d: 'person who teaches', e: 'My teacher is helpful.' },
        { w: 'professor', p: 'noun', d: 'university teacher', e: 'The professor explains well.' },
        { w: 'curriculum', p: 'noun', d: 'course of study', e: 'The curriculum is challenging.' },
        { w: 'exam', p: 'noun', d: 'test of knowledge', e: 'The exam was difficult.' },
        { w: 'degree', p: 'noun', d: 'qualification', e: 'I have a degree in math.' },
        { w: 'scholarship', p: 'noun', d: 'money for study', e: 'I won a scholarship.' },
        { w: 'lecture', p: 'noun', d: 'teaching session', e: 'The lecture was interesting.' },
        { w: 'research', p: 'noun', d: 'investigation', e: 'I do research on this topic.' },
        { w: 'thesis', p: 'noun', d: 'major assignment', e: 'My thesis is about climate.' },
        { w: 'academic', p: 'adjective', d: 'school-related', e: 'Academic writing is formal.' },
        { w: 'knowledge', p: 'noun', d: 'understanding', e: 'Knowledge is power.' },
        { w: 'skill', p: 'noun', d: 'ability', e: 'I developed many skills.' },
        { w: 'training', p: 'noun', d: 'teaching practice', e: 'The training was useful.' },
      ],
      'Health & Science': [
        { w: 'disease', p: 'noun', d: 'health condition', e: 'The disease is spreading.' },
        { w: 'medicine', p: 'noun', d: 'treatment', e: 'Take your medicine daily.' },
        { w: 'hospital', p: 'noun', d: 'health facility', e: 'I went to the hospital.' },
        { w: 'doctor', p: 'noun', d: 'medical professional', e: 'See a doctor regularly.' },
        { w: 'patient', p: 'noun', d: 'sick person', e: 'The patient needs rest.' },
        { w: 'virus', p: 'noun', d: 'tiny infection', e: 'The virus spreads easily.' },
        { w: 'vaccine', p: 'noun', d: 'prevention shot', e: 'Get your vaccine now.' },
        { w: 'treatment', p: 'noun', d: 'medical care', e: 'Treatment is effective.' },
        { w: 'symptom', p: 'noun', d: 'sign of illness', e: 'Watch for symptoms.' },
        { w: 'diagnosis', p: 'noun', d: 'health assessment', e: 'The diagnosis is clear.' },
        { w: 'experiment', p: 'noun', d: 'scientific test', e: 'The experiment succeeded.' },
        { w: 'theory', p: 'noun', d: 'explanation', e: 'Einstein\'s theory is famous.' },
        { w: 'evidence', p: 'noun', d: 'proof', e: 'The evidence is strong.' },
        { w: 'scientist', p: 'noun', d: 'research person', e: 'The scientist discovered something.' },
        { w: 'chemical', p: 'noun', d: 'substance', e: 'Chemical reactions occur.' },
      ],
      'Environment & Travel': [
        { w: 'climate', p: 'noun', d: 'weather pattern', e: 'Climate change is serious.' },
        { w: 'pollution', p: 'noun', d: 'contamination', e: 'Pollution harms the environment.' },
        { w: 'renewable', p: 'adjective', d: 'sustainable', e: 'Renewable energy is clean.' },
        { w: 'ecosystem', p: 'noun', d: 'nature system', e: 'The ecosystem is fragile.' },
        { w: 'species', p: 'noun', d: 'type of animal', e: 'Many species are endangered.' },
        { w: 'extinction', p: 'noun', d: 'dying out', e: 'Extinction is irreversible.' },
        { w: 'conservation', p: 'noun', d: 'protection', e: 'Conservation is important.' },
        { w: 'forest', p: 'noun', d: 'wooded area', e: 'The forest is beautiful.' },
        { w: 'mountain', p: 'noun', d: 'high landform', e: 'We climbed the mountain.' },
        { w: 'ocean', p: 'noun', d: 'large water body', e: 'The ocean is vast.' },
        { w: 'beach', p: 'noun', d: 'sandy shore', e: 'We relaxed at the beach.' },
        { w: 'travel', p: 'noun', d: 'going somewhere', e: 'I love to travel.' },
        { w: 'tourist', p: 'noun', d: 'visitor', e: 'Many tourists visit here.' },
        { w: 'passport', p: 'noun', d: 'travel document', e: 'Get your passport renewed.' },
        { w: 'visa', p: 'noun', d: 'entry permission', e: 'I need a visa to visit.' },
      ],
    },
  },
  fr: {
    name: 'French',
    A1: {
      'Famille et Maison': [
        { w: 'mère', p: 'noun', d: 'parent féminin', e: 'Ma mère est professeure.' },
        { w: 'père', p: 'noun', d: 'parent masculin', e: 'Mon père travaille.' },
        { w: 'soeur', p: 'noun', d: 'soeur consanguine', e: 'J\'ai deux soeurs.' },
        { w: 'frère', p: 'noun', d: 'frère consanguin', e: 'Mon frère est jeune.' },
        { w: 'famille', p: 'noun', d: 'parents et enfants', e: 'Ma famille est importante.' },
        { w: 'maison', p: 'noun', d: 'habitation', e: 'J\'habite dans une maison.' },
        { w: 'chambre', p: 'noun', d: 'pièce pour dormir', e: 'Ma chambre est petite.' },
        { w: 'cuisine', p: 'noun', d: 'pièce pour cuisiner', e: 'Je cuisine dans la cuisine.' },
        { w: 'porte', p: 'noun', d: 'entrée', e: 'Ferme la porte s\'il te plaît.' },
        { w: 'fenêtre', p: 'noun', d: 'ouverture', e: 'Ouvre la fenêtre.' },
        { w: 'lit', p: 'noun', d: 'pour dormir', e: 'Je dors dans mon lit.' },
        { w: 'chaise', p: 'noun', d: 'pour s\'asseoir', e: 'Assieds-toi sur la chaise.' },
        { w: 'table', p: 'noun', d: 'surface plate', e: 'Nous mangeons à la table.' },
        { w: 'lampe', p: 'noun', d: 'source de lumière', e: 'Allume la lampe.' },
        { w: 'téléphone', p: 'noun', d: 'appareil pour appeler', e: 'Appelle-moi sur mon téléphone.' },
      ],
      'Nourriture et Boisson': [
        { w: 'pain', p: 'noun', d: 'aliment de farine', e: 'Je mange du pain.' },
        { w: 'eau', p: 'noun', d: 'liquide clair', e: 'Buvez de l\'eau.' },
        { w: 'pomme', p: 'noun', d: 'fruit rouge ou vert', e: 'Une pomme par jour.' },
        { w: 'café', p: 'noun', d: 'boisson chaude', e: 'Je bois du café.' },
        { w: 'lait', p: 'noun', d: 'liquide blanc', e: 'Le lait est bon.' },
        { w: 'fromage', p: 'noun', d: 'produit laitier', e: 'J\'aime le fromage.' },
        { w: 'oeuf', p: 'noun', d: 'aliment pour petit déjeuner', e: 'Je mange un oeuf.' },
        { w: 'poulet', p: 'noun', d: 'viande de poule', e: 'Je mange du poulet.' },
        { w: 'riz', p: 'noun', d: 'grain de base', e: 'Je mange du riz.' },
        { w: 'poisson', p: 'noun', d: 'aliment aquatique', e: 'Le poisson est bon.' },
        { w: 'soupe', p: 'noun', d: 'aliment liquide', e: 'La soupe est chaude.' },
        { w: 'salade', p: 'noun', d: 'légumes mélangés', e: 'Je mange une salade.' },
        { w: 'thé', p: 'noun', d: 'boisson chaude', e: 'Je bois du thé.' },
        { w: 'jus', p: 'noun', d: 'boisson de fruit', e: 'Le jus d\'orange est bon.' },
        { w: 'sucre', p: 'noun', d: 'substance douce', e: 'Ajoute du sucre.' },
      ],
      'Nombres et Temps': [
        { w: 'un', p: 'noun', d: 'nombre 1', e: 'J\'ai un chat.' },
        { w: 'deux', p: 'noun', d: 'nombre 2', e: 'Nous avons deux voitures.' },
        { w: 'trois', p: 'noun', d: 'nombre 3', e: 'Il y a trois livres.' },
        { w: 'dix', p: 'noun', d: 'nombre 10', e: 'Dix doigts sur les mains.' },
        { w: 'cent', p: 'noun', d: 'nombre 100', e: 'Ce livre a 200 pages.' },
        { w: 'jour', p: 'noun', d: 'période de 24h', e: 'Je travaille cinq jours par semaine.' },
        { w: 'semaine', p: 'noun', d: 'sept jours', e: 'Je vois mon ami chaque semaine.' },
        { w: 'mois', p: 'noun', d: 'environ 30 jours', e: 'Janvier est le premier mois.' },
        { w: 'année', p: 'noun', d: '12 mois', e: 'J\'ai 25 ans.' },
        { w: 'heure', p: 'noun', d: '60 minutes', e: 'Je travaille 8 heures par jour.' },
        { w: 'minute', p: 'noun', d: '60 secondes', e: 'Attends cinq minutes.' },
        { w: 'seconde', p: 'noun', d: '1/60 minute', e: 'Une seconde s\'il te plaît.' },
        { w: 'matin', p: 'noun', d: 'début du jour', e: 'Je me réveille le matin.' },
        { w: 'après-midi', p: 'noun', d: 'milieu du jour', e: 'Je me repose l\'après-midi.' },
        { w: 'soir', p: 'noun', d: 'fin du jour', e: 'Je dîne le soir.' },
      ],
      'Couleurs et Formes': [
        { w: 'rouge', p: 'adjective', d: 'couleur du sang', e: 'Elle a une voiture rouge.' },
        { w: 'bleu', p: 'adjective', d: 'couleur du ciel', e: 'Le ciel est bleu.' },
        { w: 'vert', p: 'adjective', d: 'couleur de l\'herbe', e: 'Les arbres sont verts.' },
        { w: 'jaune', p: 'adjective', d: 'couleur du soleil', e: 'La fleur est jaune.' },
        { w: 'blanc', p: 'adjective', d: 'couleur de la neige', e: 'Sa chemise est blanche.' },
        { w: 'noir', p: 'adjective', d: 'couleur la plus sombre', e: 'J\'ai un stylo noir.' },
        { w: 'cercle', p: 'noun', d: 'forme ronde', e: 'Une balle est un cercle.' },
        { w: 'carré', p: 'noun', d: 'quatre côtés égaux', e: 'Une boîte est carrée.' },
        { w: 'triangle', p: 'noun', d: 'forme à trois côtés', e: 'Une pyramide a des triangles.' },
        { w: 'ligne', p: 'noun', d: 'marque droite', e: 'Dessine une ligne.' },
      ],
      'Parties du Corps': [
        { w: 'tête', p: 'noun', d: 'haut du corps', e: 'J\'ai une tête sur les épaules.' },
        { w: 'bras', p: 'noun', d: 'membre de mouvement', e: 'J\'ai deux bras.' },
        { w: 'jambe', p: 'noun', d: 'membre pour marcher', e: 'J\'ai deux jambes.' },
        { w: 'main', p: 'noun', d: 'fin du bras', e: 'J\'ai deux mains.' },
        { w: 'pied', p: 'noun', d: 'fin de la jambe', e: 'J\'ai deux pieds.' },
        { w: 'oeil', p: 'noun', d: 'organe de vision', e: 'J\'ai deux yeux.' },
        { w: 'oreille', p: 'noun', d: 'organe d\'écoute', e: 'J\'ai deux oreilles.' },
        { w: 'nez', p: 'noun', d: 'organe d\'odeur', e: 'J\'ai un nez.' },
        { w: 'bouche', p: 'noun', d: 'pour manger et parler', e: 'J\'utilise ma bouche pour manger.' },
        { w: 'dent', p: 'noun', d: 'dans la bouche', e: 'J\'ai des dents blanches.' },
      ],
    },
    B1: {
      'Affaires et Travail': [
        { w: 'profit', p: 'noun', d: 'argent gagné après frais', e: 'L\'entreprise a un grand profit.' },
        { w: 'investissement', p: 'noun', d: 'argent pour retour', e: 'L\'immobilier est un investissement.' },
        { w: 'marché', p: 'noun', d: 'lieu de commerce', e: 'Le marché boursier a augmenté.' },
        { w: 'entrepreneur', p: 'noun', d: 'créateur d\'entreprise', e: 'Elle est entrepreneur réussie.' },
        { w: 'contrat', p: 'noun', d: 'accord légal', e: 'Nous avons signé le contrat.' },
        { w: 'salaire', p: 'noun', d: 'paiement du travail', e: 'Mon salaire est payé mensuellement.' },
        { w: 'employé', p: 'noun', d: 'personne qui travaille', e: 'La société a 500 employés.' },
        { w: 'employeur', p: 'noun', d: 'personne qui embauche', e: 'Mon employeur est gentil.' },
        { w: 'collègue', p: 'noun', d: 'compagnon de travail', e: 'Je travaille avec mon collègue.' },
        { w: 'bureau', p: 'noun', d: 'lieu de travail', e: 'Je travaille dans un grand bureau.' },
        { w: 'conférence', p: 'noun', d: 'réunion d\'affaires', e: 'Nous avons une conférence demain.' },
        { w: 'délai', p: 'noun', d: 'date limite', e: 'Le délai est vendredi.' },
        { w: 'budget', p: 'noun', d: 'plan d\'argent', e: 'Nous avons un budget serré.' },
        { w: 'revenu', p: 'noun', d: 'argent gagné', e: 'Notre revenu a augmenté cette année.' },
        { w: 'dépense', p: 'noun', d: 'argent dépensé', e: 'Les frais d\'affaires sont élevés.' },
      ],
      'Technologie': [
        { w: 'logiciel', p: 'noun', d: 'programmes informatiques', e: 'Ce logiciel est convivial.' },
        { w: 'base de données', p: 'noun', d: 'données organisées', e: 'La base contient les infos clients.' },
        { w: 'interface', p: 'noun', d: 'dispositif connectant', e: 'L\'interface est facile à utiliser.' },
        { w: 'algorithme', p: 'noun', d: 'procédure étape par étape', e: 'L\'algorithme résout vite.' },
        { w: 'bande passante', p: 'noun', d: 'capacité de transmission', e: 'Nous avons besoin de plus de bande passante.' },
        { w: 'serveur', p: 'noun', d: 'ordinateur principal', e: 'Le serveur est en panne.' },
        { w: 'nuage', p: 'noun', d: 'stockage distant', e: 'Sauvegarde tes fichiers dans le nuage.' },
        { w: 'réseau', p: 'noun', d: 'ordinateurs connectés', e: 'Le réseau est sécurisé.' },
        { w: 'sécurité', p: 'noun', d: 'système de protection', e: 'La sécurité est importante en ligne.' },
        { w: 'chiffrement', p: 'noun', d: 'protection de données', e: 'Le chiffrement sécurise les données.' },
        { w: 'cyber', p: 'adjective', d: 'relié à l\'informatique', e: 'Les cyberattaques sont dangereuses.' },
        { w: 'numérique', p: 'adjective', d: 'utilisant des ordinateurs', e: 'La transformation numérique est en cours.' },
        { w: 'virtuel', p: 'adjective', d: 'non physique', e: 'Les réunions virtuelles sont courantes.' },
        { w: 'artificiel', p: 'adjective', d: 'fait par l\'homme', e: 'L\'intelligence artificielle grandit.' },
        { w: 'innovation', p: 'noun', d: 'nouvelle création', e: 'L\'innovation pousse le progrès.' },
      ],
      'Éducation': [
        { w: 'université', p: 'noun', d: 'lieu d\'enseignement supérieur', e: 'Je vais à l\'université.' },
        { w: 'étudiant', p: 'noun', d: 'personne qui apprend', e: 'L\'étudiant travaille dur.' },
        { w: 'professeur', p: 'noun', d: 'personne qui enseigne', e: 'Mon professeur est utile.' },
        { w: 'professeur d\'université', p: 'noun', d: 'enseignant universitaire', e: 'Le professeur d\'université explique bien.' },
        { w: 'curriculum', p: 'noun', d: 'cours d\'étude', e: 'Le curriculum est difficile.' },
        { w: 'examen', p: 'noun', d: 'test de connaissances', e: 'L\'examen était difficile.' },
        { w: 'diplôme', p: 'noun', d: 'qualification', e: 'J\'ai un diplôme en mathématiques.' },
        { w: 'bourse', p: 'noun', d: 'argent pour étudier', e: 'J\'ai gagné une bourse.' },
        { w: 'cours magistral', p: 'noun', d: 'session d\'enseignement', e: 'Le cours était intéressant.' },
        { w: 'recherche', p: 'noun', d: 'investigation', e: 'Je fais de la recherche sur ce sujet.' },
        { w: 'thèse', p: 'noun', d: 'grand travail', e: 'Ma thèse parle du climat.' },
        { w: 'académique', p: 'adjective', d: 'relié à l\'école', e: 'L\'écriture académique est formelle.' },
        { w: 'connaissance', p: 'noun', d: 'compréhension', e: 'La connaissance est le pouvoir.' },
        { w: 'compétence', p: 'noun', d: 'capacité', e: 'J\'ai développé beaucoup de compétences.' },
        { w: 'formation', p: 'noun', d: 'enseignement pratique', e: 'La formation était utile.' },
      ],
      'Santé et Science': [
        { w: 'maladie', p: 'noun', d: 'condition de santé', e: 'La maladie se propage.' },
        { w: 'médicament', p: 'noun', d: 'traitement', e: 'Prends ton médicament quotidiennement.' },
        { w: 'hôpital', p: 'noun', d: 'établissement de santé', e: 'Je suis allé à l\'hôpital.' },
        { w: 'docteur', p: 'noun', d: 'professionnel médical', e: 'Vois un docteur régulièrement.' },
        { w: 'patient', p: 'noun', d: 'personne malade', e: 'Le patient a besoin de repos.' },
        { w: 'virus', p: 'noun', d: 'petite infection', e: 'Le virus se propage facilement.' },
        { w: 'vaccin', p: 'noun', d: 'injection préventive', e: 'Fais-toi vacciner maintenant.' },
        { w: 'traitement', p: 'noun', d: 'soin médical', e: 'Le traitement est efficace.' },
        { w: 'symptôme', p: 'noun', d: 'signe de maladie', e: 'Observe les symptômes.' },
        { w: 'diagnostic', p: 'noun', d: 'évaluation de santé', e: 'Le diagnostic est clair.' },
        { w: 'expérience', p: 'noun', d: 'test scientifique', e: 'L\'expérience a réussi.' },
        { w: 'théorie', p: 'noun', d: 'explication', e: 'La théorie d\'Einstein est célèbre.' },
        { w: 'preuve', p: 'noun', d: 'evidence', e: 'La preuve est solide.' },
        { w: 'scientifique', p: 'noun', d: 'personne de recherche', e: 'Le scientifique a découvert quelque chose.' },
        { w: 'chimique', p: 'noun', d: 'substance', e: 'Les réactions chimiques se produisent.' },
      ],
      'Environnement et Voyage': [
        { w: 'climat', p: 'noun', d: 'pattern de temps', e: 'Le changement climatique est grave.' },
        { w: 'pollution', p: 'noun', d: 'contamination', e: 'La pollution nuit à l\'environnement.' },
        { w: 'renouvelable', p: 'adjective', d: 'durable', e: 'L\'énergie renouvelable est propre.' },
        { w: 'écosystème', p: 'noun', d: 'système naturel', e: 'L\'écosystème est fragile.' },
        { w: 'espèce', p: 'noun', d: 'type d\'animal', e: 'De nombreuses espèces sont menacées.' },
        { w: 'extinction', p: 'noun', d: 'disparition', e: 'L\'extinction est irréversible.' },
        { w: 'conservation', p: 'noun', d: 'protection', e: 'La conservation est importante.' },
        { w: 'forêt', p: 'noun', d: 'zone boisée', e: 'La forêt est belle.' },
        { w: 'montagne', p: 'noun', d: 'formation élevée', e: 'Nous avons grimpé la montagne.' },
        { w: 'océan', p: 'noun', d: 'grand plan d\'eau', e: 'L\'océan est vaste.' },
        { w: 'plage', p: 'noun', d: 'côte sablonneuse', e: 'Nous avons relaxé à la plage.' },
        { w: 'voyage', p: 'noun', d: 'aller quelque part', e: 'J\'aime voyager.' },
        { w: 'touriste', p: 'noun', d: 'visiteur', e: 'Beaucoup de touristes viennent ici.' },
        { w: 'passeport', p: 'noun', d: 'document de voyage', e: 'Renouvelle ton passeport.' },
        { w: 'visa', p: 'noun', d: 'permission d\'entrée', e: 'J\'ai besoin d\'un visa pour visiter.' },
      ],
    },
  },
  zh: {
    name: 'Chinese',
    A1: {
      '家庭和家': [
        { w: '母亲', p: 'noun', d: '女性父母', e: '我的母亲是一名教师。' },
        { w: '父亲', p: 'noun', d: '男性父母', e: '我的父亲工作很努力。' },
        { w: '姐妹', p: 'noun', d: '女性兄弟姐妹', e: '我有两个姐妹。' },
        { w: '兄弟', p: 'noun', d: '男性兄弟姐妹', e: '我有两个兄弟。' },
        { w: '家庭', p: 'noun', d: '父母和孩子', e: '家庭很重要。' },
        { w: '房子', p: 'noun', d: '居住的建筑', e: '我们有一栋大房子。' },
        { w: '房间', p: 'noun', d: '建筑中的空间', e: '我的卧室很小。' },
        { w: '厨房', p: 'noun', d: '烹饪的地方', e: '我在厨房里做饭。' },
        { w: '门', p: 'noun', d: '房间的入口', e: '请关上门。' },
        { w: '窗户', p: 'noun', d: '墙上的开口', e: '打开窗户。' },
        { w: '床', p: 'noun', d: '睡觉的家具', e: '我在床上睡觉。' },
        { w: '椅子', p: 'noun', d: '坐的家具', e: '请坐在椅子上。' },
        { w: '桌子', p: 'noun', d: '平面家具', e: '我们在桌子上吃饭。' },
        { w: '灯', p: 'noun', d: '发光的物体', e: '打开灯。' },
        { w: '电话', p: 'noun', d: '通话设备', e: '在我的电话上给我打电话。' },
      ],
      '食物和饮料': [
        { w: '面包', p: 'noun', d: '由面粉制成的食物', e: '我每天吃面包。' },
        { w: '水', p: 'noun', d: '清澈的液体', e: '定期喝水。' },
        { w: '苹果', p: 'noun', d: '圆形红色或绿色水果', e: '一天一苹果保健康。' },
        { w: '咖啡', p: 'noun', d: '热饮料', e: '我每天早上喝咖啡。' },
        { w: '牛奶', p: 'noun', d: '来自动物的白色液体', e: '牛奶对骨骼有益。' },
        { w: '奶酪', p: 'noun', d: '乳制品', e: '我喜欢面包和奶酪。' },
        { w: '鸡蛋', p: 'noun', d: '早餐食物', e: '我早餐吃一个鸡蛋。' },
        { w: '鸡肉', p: 'noun', d: '鸡的肉', e: '我们晚餐吃鸡肉。' },
        { w: '米', p: 'noun', d: '谷物主食', e: '我每天吃米。' },
        { w: '鱼', p: 'noun', d: '来自水的食物', e: '鱼对身体很好。' },
        { w: '汤', p: 'noun', d: '液体食物', e: '汤温暖又美味。' },
        { w: '沙拉', p: 'noun', d: '蔬菜混合在一起', e: '我吃一个健康的沙拉。' },
        { w: '茶', p: 'noun', d: '来自叶子的热饮料', e: '我下午喝茶。' },
        { w: '果汁', p: 'noun', d: '来自水果的饮料', e: '橙汁很美味。' },
        { w: '糖', p: 'noun', d: '甜物质', e: '给咖啡加糖。' },
      ],
    },
    B1: {
      '商业和工作': [
        { w: '利润', p: 'noun', d: '成本后赚取的钱', e: '公司今年获得了大利润。' },
        { w: '投资', p: 'noun', d: '为了获得回报而投入的钱', e: '房地产是一项很好的投资。' },
        { w: '市场', p: 'noun', d: '商品买卖的地方', e: '股票市场今天上升了。' },
        { w: '企业家', p: 'noun', d: '创办企业的人', e: '她是一位成功的企业家。' },
        { w: '合同', p: 'noun', d: '法律协议', e: '我们昨天签署了合同。' },
        { w: '薪资', p: 'noun', d: '工作的报酬', e: '我的薪资按月支付。' },
        { w: '员工', p: 'noun', d: '工作的人', e: '公司有500名员工。' },
        { w: '雇主', p: 'noun', d: '雇人的人', e: '我的雇主很友善。' },
        { w: '同事', p: 'noun', d: '同事', e: '我和同事一起工作。' },
        { w: '办公室', p: 'noun', d: '工作场所', e: '我在一个大办公室工作。' },
        { w: '会议', p: 'noun', d: '商务会议', e: '我们明天有一个会议。' },
        { w: '截止日期', p: 'noun', d: '最后日期', e: '截止日期是星期五。' },
        { w: '预算', p: 'noun', d: '金钱计划', e: '我们的预算很紧张。' },
        { w: '收入', p: 'noun', d: '赚取的钱', e: '我们的收入今年增长了。' },
        { w: '支出', p: 'noun', d: '花费的钱', e: '商业支出很高。' },
      ],
    },
  },
  ja: {
    name: 'Japanese',
    A1: {
      '家族と家': [
        { w: '母親', p: 'noun', d: '女性の親', e: '私の母親は先生です。' },
        { w: '父親', p: 'noun', d: '男性の親', e: '私の父親はオフィスで働いています。' },
        { w: '姉妹', p: 'noun', d: '女性の兄弟姉妹', e: '私は2人の姉妹がいます。' },
        { w: '兄弟', p: 'noun', d: '男性の兄弟姉妹', e: '私の兄弟は私より若い。' },
        { w: '家族', p: 'noun', d: '両親と子供たち', e: '家族は私にとって非常に重要です。' },
        { w: '家', p: 'noun', d: '住む建物', e: '私たちは大きな家を持っています。' },
        { w: '部屋', p: 'noun', d: '建物内のスペース', e: '私の寝室は小さいです。' },
        { w: 'キッチン', p: 'noun', d: '料理をする部屋', e: 'キッチンで料理をします。' },
        { w: 'ドア', p: 'noun', d: '部屋の入り口', e: 'ドアを閉めてください。' },
        { w: '窓', p: 'noun', d: '壁の開口部', e: '窓を開けてください。' },
        { w: 'ベッド', p: 'noun', d: '寝るための家具', e: '私はベッドで寝ます。' },
        { w: '椅子', p: 'noun', d: '座る家具', e: '椅子に座ってください。' },
        { w: 'テーブル', p: 'noun', d: '平らな家具の表面', e: 'テーブルで食事をします。' },
        { w: 'ランプ', p: 'noun', d: '光を発するもの', e: 'ランプを点けてください。' },
        { w: '電話', p: 'noun', d: '通話装置', e: '私の電話で電話してください。' },
      ],
    },
  },
  pt: {
    name: 'Portuguese',
    A1: {
      'Família e Casa': [
        { w: 'mãe', p: 'noun', d: 'progenitora', e: 'Minha mãe é professora.' },
        { w: 'pai', p: 'noun', d: 'progenitor', e: 'Meu pai trabalha com afinco.' },
        { w: 'irmã', p: 'noun', d: 'irmã consanguínea', e: 'Tenho duas irmãs.' },
        { w: 'irmão', p: 'noun', d: 'irmão consanguíneo', e: 'Meu irmão é mais jovem que eu.' },
        { w: 'família', p: 'noun', d: 'pais e filhos', e: 'A família é importante.' },
        { w: 'casa', p: 'noun', d: 'edifício para viver', e: 'Temos uma casa grande.' },
        { w: 'quarto', p: 'noun', d: 'espaço em um edifício', e: 'Meu quarto é pequeno.' },
        { w: 'cozinha', p: 'noun', d: 'sala para cozinhar', e: 'Cozinho na cozinha.' },
        { w: 'porta', p: 'noun', d: 'entrada de uma sala', e: 'Feche a porta por favor.' },
        { w: 'janela', p: 'noun', d: 'abertura em uma parede', e: 'Abra a janela.' },
        { w: 'cama', p: 'noun', d: 'móvel para dormir', e: 'Durmo em minha cama.' },
        { w: 'cadeira', p: 'noun', d: 'móvel para sentar', e: 'Sente-se na cadeira.' },
        { w: 'mesa', p: 'noun', d: 'superfície móvel plana', e: 'Comemos na mesa.' },
        { w: 'lâmpada', p: 'noun', d: 'objeto que dá luz', e: 'Acenda a lâmpada.' },
        { w: 'telefone', p: 'noun', d: 'dispositivo para ligar', e: 'Ligue para mim no meu telefone.' },
      ],
    },
  },
  it: {
    name: 'Italian',
    A1: {
      'Famiglia e Casa': [
        { w: 'madre', p: 'noun', d: 'genitrice', e: 'Mia madre è un\'insegnante.' },
        { w: 'padre', p: 'noun', d: 'genitore', e: 'Mio padre lavora sodo.' },
        { w: 'sorella', p: 'noun', d: 'sorella consanguinea', e: 'Ho due sorelle.' },
        { w: 'fratello', p: 'noun', d: 'fratello consanguineo', e: 'Mio fratello è più giovane di me.' },
        { w: 'famiglia', p: 'noun', d: 'genitori e figli', e: 'La famiglia è importante.' },
        { w: 'casa', p: 'noun', d: 'edificio dove vivere', e: 'Abbiamo una casa grande.' },
        { w: 'camera', p: 'noun', d: 'spazio in un edificio', e: 'La mia camera è piccola.' },
        { w: 'cucina', p: 'noun', d: 'stanza per cucinare', e: 'Cucino in cucina.' },
        { w: 'porta', p: 'noun', d: 'ingresso di una stanza', e: 'Chiudi la porta per favore.' },
        { w: 'finestra', p: 'noun', d: 'apertura in una parete', e: 'Apri la finestra.' },
        { w: 'letto', p: 'noun', d: 'mobile per dormire', e: 'Dormo nel mio letto.' },
        { w: 'sedia', p: 'noun', d: 'mobile per sedersi', e: 'Siediti sulla sedia.' },
        { w: 'tavolo', p: 'noun', d: 'superficie mobile piatta', e: 'Mangiamo al tavolo.' },
        { w: 'lampada', p: 'noun', d: 'oggetto che dà luce', e: 'Accendi la lampada.' },
        { w: 'telefono', p: 'noun', d: 'dispositivo per chiamare', e: 'Chiamami al mio telefono.' },
      ],
    },
  },
  es: {
    name: 'Spanish',
    A1: {
      'Familia y Casa': [
        { w: 'madre', p: 'noun', d: 'progenitora', e: 'Mi madre es una maestra.' },
        { w: 'padre', p: 'noun', d: 'progenitor', e: 'Mi padre trabaja duro.' },
        { w: 'hermana', p: 'noun', d: 'hermana consanguínea', e: 'Tengo dos hermanas.' },
        { w: 'hermano', p: 'noun', d: 'hermano consanguíneo', e: 'Mi hermano es más joven que yo.' },
        { w: 'familia', p: 'noun', d: 'padres e hijos', e: 'La familia es importante.' },
        { w: 'casa', p: 'noun', d: 'edificio para vivir', e: 'Tenemos una casa grande.' },
        { w: 'cuarto', p: 'noun', d: 'espacio en un edificio', e: 'Mi habitación es pequeña.' },
        { w: 'cocina', p: 'noun', d: 'sala para cocinar', e: 'Cocino en la cocina.' },
        { w: 'puerta', p: 'noun', d: 'entrada de una sala', e: 'Cierra la puerta por favor.' },
        { w: 'ventana', p: 'noun', d: 'abertura en una pared', e: 'Abre la ventana.' },
        { w: 'cama', p: 'noun', d: 'mueble para dormir', e: 'Duermo en mi cama.' },
        { w: 'silla', p: 'noun', d: 'mueble para sentarse', e: 'Siéntate en la silla.' },
        { w: 'mesa', p: 'noun', d: 'superficie de mueble plana', e: 'Comemos en la mesa.' },
        { w: 'lámpara', p: 'noun', d: 'objeto que da luz', e: 'Enciende la lámpara.' },
        { w: 'teléfono', p: 'noun', d: 'dispositivo para llamar', e: 'Llámame en mi teléfono.' },
      ],
    },
  },
  ko: {
    name: 'Korean',
    A1: {
      '가족과 집': [
        { w: '어머니', p: 'noun', d: '어머니', e: '나의 어머니는 교사입니다.' },
        { w: '아버지', p: 'noun', d: '아버지', e: '나의 아버지는 열심히 일합니다.' },
        { w: '누나/언니', p: 'noun', d: '여성 형제', e: '나는 두 명의 누나/언니가 있습니다.' },
        { w: '형/오빠', p: 'noun', d: '남성 형제', e: '나의 형/오빠는 나보다 어립니다.' },
        { w: '가족', p: 'noun', d: '부모와 자녀', e: '가족은 중요합니다.' },
        { w: '집', p: 'noun', d: '사는 건물', e: '우리는 큰 집을 가지고 있습니다.' },
        { w: '방', p: 'noun', d: '건물 안의 공간', e: '나의 방은 작습니다.' },
        { w: '주방', p: 'noun', d: '요리하는 방', e: '나는 주방에서 요리합니다.' },
        { w: '문', p: 'noun', d: '방의 입구', e: '문을 닫으세요.' },
        { w: '창문', p: 'noun', d: '벽의 개구부', e: '창문을 열으세요.' },
        { w: '침대', p: 'noun', d: '잠자는 가구', e: '나는 침대에서 자니다.' },
        { w: '의자', p: 'noun', d: '앉는 가구', e: '의자에 앉으세요.' },
        { w: '테이블', p: 'noun', d: '평평한 가구 표면', e: '테이블에서 식사합니다.' },
        { w: '램프', p: 'noun', d: '빛을 주는 물체', e: '램프를 켜세요.' },
        { w: '전화', p: 'noun', d: '통화 장치', e: '내 전화로 전화하세요.' },
      ],
    },
  },
};

function generateExpandedVocabulary(count, language, level, topic = null) {
  const words = [];
  const langData = EXPANDED_VOCABULARY[language] || EXPANDED_VOCABULARY['en'];
  const levelData = langData[level] || langData['A1'];

  const availableTopics = Object.keys(levelData);
  let topicsToUse = availableTopics;

  if (topic && levelData[topic]) {
    topicsToUse = [topic];
  }

  let wordIndex = 0;
  for (const topicName of topicsToUse) {
    const topicWords = levelData[topicName] || [];

    for (const wordData of topicWords) {
      if (wordIndex >= count) break;

      words.push({
        word: wordData.w,
        definition: wordData.d,
        exampleSentence: wordData.e,
        partOfSpeech: wordData.p,
        topic: topicName,
        level: level,
      });
      wordIndex++;
    }

    if (wordIndex >= count) break;
  }

  // Pad if needed
  while (words.length < count && words.length > 0) {
    const randomWord = words[Math.floor(Math.random() * words.length)];
    words.push({
      ...randomWord,
      word: randomWord.word + '_' + (words.length + 1),
    });
  }

  return words;
}

module.exports = {
  generateExpandedVocabulary,
  EXPANDED_VOCABULARY,
};
