module.exports = {
  DELF: {
    name: 'DELF',
    language: { name: 'French', code: 'fr', icon: '🇫🇷' },
    description: 'Diplôme d\'Études en Langue Française.',
    levels: ['A1', 'A2', 'B1', 'B2'],
    sections: ['reading', 'writing-task-1', 'writing-task-2', 'speaking-part-1', 'speaking-part-2', 'speaking-part-3'],
    questionsPerSection: 150,
    questionsPerSpeakingPart: 40,
    durationMinutes: 200,
    scoringType: 'score',
    maxScore: 250,
  },
  Goethe: {
    name: 'Goethe-Zertifikat',
    language: { name: 'German', code: 'de', icon: '🇩🇪' },
    description: 'Goethe-Institut German proficiency exam.',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    sections: ['reading', 'writing-task-1', 'writing-task-2', 'speaking-part-1', 'speaking-part-2', 'speaking-part-3'],
    questionsPerSection: 150,
    questionsPerSpeakingPart: 40,
    durationMinutes: 210,
    scoringType: 'score',
    maxScore: 300,
  },
  HSK: {
    name: 'HSK',
    language: { name: 'Chinese (Mandarin)', code: 'zh', icon: '🇨🇳' },
    description: 'Hanyu Shuiping Kaoshi (Chinese proficiency test).',
    levels: ['HSK 1', 'HSK 2', 'HSK 3', 'HSK 4', 'HSK 5', 'HSK 6'],
    sections: ['reading', 'writing-task-1', 'writing-task-2', 'speaking-part-1', 'speaking-part-2', 'speaking-part-3'],
    questionsPerSection: 150,
    questionsPerSpeakingPart: 40,
    durationMinutes: 200,
    scoringType: 'score',
    maxScore: 300,
  },
  JLPT: {
    name: 'JLPT',
    language: { name: 'Japanese', code: 'ja', icon: '🇯🇵' },
    description: 'Japanese Language Proficiency Test.',
    levels: ['N5', 'N4', 'N3', 'N2', 'N1'],
    sections: ['reading', 'writing-task-1', 'writing-task-2', 'speaking-part-1', 'speaking-part-2', 'speaking-part-3'],
    questionsPerSection: 150,
    questionsPerSpeakingPart: 40,
    durationMinutes: 180,
    scoringType: 'score',
    maxScore: 180,
  },
  CAPLE: {
    name: 'CAPLE',
    language: { name: 'Portuguese', code: 'pt', icon: '🇵🇹' },
    description: 'Cambridge English Certificate – Portuguese.',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    sections: ['reading', 'writing-task-1', 'writing-task-2', 'speaking-part-1', 'speaking-part-2', 'speaking-part-3'],
    questionsPerSection: 150,
    questionsPerSpeakingPart: 40,
    durationMinutes: 210,
    scoringType: 'score',
    maxScore: 230,
  },
  CELI: {
    name: 'CELI',
    language: { name: 'Italian', code: 'it', icon: '🇮🇹' },
    description: 'Certificato di Conoscenza della Lingua Italiana.',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    sections: ['reading', 'writing-task-1', 'writing-task-2', 'speaking-part-1', 'speaking-part-2', 'speaking-part-3'],
    questionsPerSection: 150,
    questionsPerSpeakingPart: 40,
    durationMinutes: 210,
    scoringType: 'score',
    maxScore: 200,
  },
};
